name: main
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: false
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:
  capa_de_jornal:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.PAT_GITHUB }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      
      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: Install packages
        run: |   
          install.packages("webshot2")
        shell: Rscript {0}
        
      - name: Take screenshots
        id: retry
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 5
          retry_on: error
          continue_on_error: true
          command: Rscript screenshot_script.R
        
      - name: Take g1 screenshots
        id: retry_g1
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 5
          retry_on: error
          continue_on_error: true
          command: Rscript screenshot_g1_script.R
        
      - name: Commit results
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add screenshots/*
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
          
      
