name: teste
on: 
  schedule:
  - cron: '0 11 * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: false
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:
  print_dos_sites:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.PAT_GITHUB }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      
      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: Install packages
        run: |   
          install.packages(c("webshot2","purrr","dplyr"))
        shell: Rscript {0}
         
      - name: Commit removal
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git rm screenshots/*
          git add screenshots/
          git commit -m "Remove data: ${timestamp}" || exit 0
          git push
        
      - name: Take screenshots and partial commit
        id: retry
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 5
          retry_on: error
          continue_on_error: true
          command: Rscript screenshot_script.R
          on_retry_command: |
            git config user.name "Automated"
            git config user.email "actions@users.noreply.github.com"
            git add screenshots/*
            git commit -m "Latest data: ${timestamp}" || exit 0
            git push
            
      - name: Commit final results
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add screenshots/*
          git commit -m "Remove data: ${timestamp}" || exit 0
          git push
